# Generated by Django 4.1 on 2022-09-27 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_order_options_product_image_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='profile-img2.jpg', upload_to='Profile_Images'),
        ),
    ]
