# Generated by Django 4.1 on 2022-10-01 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_product_image_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='electronics.jpg', upload_to='E-Waste Materials'),
        ),
    ]
