# Generated by Django 4.1 on 2022-10-07 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='product',
            new_name='name',
        ),
    ]
