# Generated by Django 4.1.2 on 2022-11-13 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='building',
            field=models.CharField(default='Building', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='county',
            field=models.CharField(default='Nairobi', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='location',
            field=models.CharField(default='Nairobi', max_length=200, null=True),
        ),
    ]
