# Generated by Django 4.1 on 2022-10-11 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_product_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={},
        ),
    ]
