# Generated by Django 4.1 on 2022-10-11 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_order_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='E-Waste', upload_to='Profile_Images'),
        ),
    ]
